name: Update Changelog

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Generate changelog for release
        uses: orhun/git-cliff-action@v3
        id: git-cliff-release
        with:
          config: cliff.toml
          args: --verbose
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Update Changelog
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: ${{ steps.git-cliff-release.outputs.changelog }}
          message: 'docs: update CHANGELOG.md'
