name: Update Changelog

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog for release
        uses: orhun/git-cliff-action@v3
        id: git-cliff-release
        with:
          config: cliff.toml
          args: --verbose
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Update Changelog
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ${{ steps.git-cliff-release.outputs.changelog }}
          git commit -m "Update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main  # 修改为您的目标分支
