name: Create Changelog

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate full changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff-full
        with:
          config: cliff.toml
          args: --output CHANGELOG.md
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit updated CHANGELOG.md
        id: commit-changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update CHANGELOG.md"
          file_pattern: CHANGELOG.md
          branch: ${{ github.event.repository.default_branch }}

      - name: Generate changelog for release
        uses: orhun/git-cliff-action@v3
        id: git-cliff-release
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Update tag ref
        run: |
          git push origin :refs/tags/${{ github.ref_name }}
          git tag -fa ${{ github.ref_name }} -m "chore: update tag with changelog"
          git push origin ${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.git-cliff-release.outputs.content }}
          tag_name: ${{ github.ref_name }}
