name: Create Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{steps.github_release.outputs.changelog}}
