name: Solhint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  solhint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.x
        run_install: true
        
    - name: Solhint Contracts
      run: pnpm solhint contracts/**/*.sol